### ISSUE TITLE
Filter overriding existing material and texture settings, not just imported

### ISSUE THREAD

**Issue by XDelta** [Toxic-Cookie/DefaultToAnisotropic#4]
If I pull out the MainTexture on a material, it will be overwritten with the set filtering, despite it already existing (Not a fresh import). Specifically noticed on small <128x128 textures that are set to point filtering.

**Comment by BlueCyro** [comment]
Just adding that this is because the ImageImporter.SetupTextureProxyComponents function is used to construct the reference proxy when you grab it. Always be sure to check what stuff calls a function being patched.

**Comment by Toxic-Cookie** [comment]
Fixed as of: https://github.com/Toxic-Cookie/DefaultToAnisotropic/releases/tag/1.3.1
